# Generated by Django 4.1.7 on 2023-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crosswordApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="crossword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=50)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
