# Generated by Django 4.1.7 on 2023-03-20 21:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("crosswordApp", "0002_crossword"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossword",
            name="clues_hor",
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="crossword",
            name="clues_ver",
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="crossword",
            name="creator",
            field=models.CharField(default="admin", max_length=50),
        ),
        migrations.AddField(
            model_name="crossword",
            name="grid",
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
